### ISSUE TITLE
AVS-SDK missing source code

### ISSUE THREAD

**Issue by mjadams** [espressif/esp-avs-sdk#1]
The AVS-SDK is currently missing all source code. Additionally, the hardware guide is missing the schematics for the microphone array board.

**Comment by ameyinamdar** [comment]
Hi @mjadams,

We are in a process of releasing the sources for the AVS-SDK, please stay tuned.

For the hardware guide and schematic, please refer to https://www.espressif.com/sites/default/files/documentation/esp32-lyratd-msc_user_guide_en.pdf

Thanks,
Amey

**Comment by mjadams** [comment]
I look forward to assisting with a custom implementation of this AWS Alexa AVS Device when the source-code is released. Alternatively I will get in touch directly with Espressif through your Angus and Teo.

**Comment by ameyinamdar** [comment]
@mjadams The source is now available on GitHub for application developers to build AVS based apps.
