### ISSUE TITLE
 LyraT board " FAILED: avs.elf "

### ISSUE THREAD

**Issue by Marcoz08** [espressif/esp-avs-sdk#162]
Hi, I am a beginner in IDF esp programming, I have been using the Lyrat board with the ADF. Now I want to use the va-sdk, specifically the amazon_alexa example, but i can´t compile the code.

I have the next error, please help me.

Best regards.

I use the windows terminal.

C:\esp-va-sdk\examples\amazon_alexa>idf.py build
Executing action: all (aliases: build)
Running ninja in directory c:\esp-va-sdk\examples\amazon_alexa\build
Executing "ninja all"...
[1/5] Performing build step for 'bootloader'
ninja: no work to do.
[2/3] Linking CXX executable avs.elf
FAILED: avs.elf
cmd.exe /C "cd . && C:\Users\MARCOZ\.espressif\tools\xtensa-esp32-elf\esp-2021r1-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe  -mlongcalls -Wno-frame-address   @CMakeFiles\avs.elf.rsp  -o avs.elf  && cd ."
c:/users/marcoz/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/esp-va-sdk/components/esp-ssdp/lib/libesp-ssdp.a(lssdp.c.obj):(.literal.trim_spaces+0x0): undefined reference to `__locale_ctype_ptr'
c:/users/marcoz/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/esp-va-sdk/components/esp-ssdp/lib/libesp-ssdp.a(lssdp.c.obj):(.text.trim_spaces+0x20): undefined reference to `__locale_ctype_ptr'
c:/users/marcoz/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/esp-va-sdk/components/esp-ssdp/lib/libesp-ssdp.a(lssdp.c.obj):(.text.trim_spaces+0x38): undefined reference to `__locale_ctype_ptr'
c:/users/marcoz/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/esp-va-sdk/components/esp-ssdp/lib/libesp-ssdp.a(lssdp.c.obj):(.text.trim_spaces+0x51): undefined reference to `__locale_ctype_ptr'
c:/users/marcoz/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/esp-va-sdk/components/esp-ssdp/lib/libesp-ssdp.a(lssdp.c.obj):(.text.trim_spaces+0x6a): undefined reference to `__locale_ctype_ptr'
c:/users/marcoz/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/esp-va-sdk/components/voice_assistant/lib/libavs.a(dialog.c.obj):(.literal.dialog_sm_thread+0x30): undefined reference to `xTaskNotify'
c:/users/marcoz/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/esp-va-sdk/components/voice_assistant/lib/libavs.a(dialog.c.obj):(.text.dialog_sm_thread+0xae): undefined reference to `xTaskNotify'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by avsheth** [comment]
Hi @Marcoz08 
Which IDF branch are you on?

**Comment by chaitanya-smartrotamac** [comment]
I got a similar issue when I used IDF branch 4.3.3 so I reverted to 4.2 and build everything now working try it.

**Comment by Marcoz08** [comment]
> Hi @Marcoz08 Which IDF branch are you on?

ESP-IDF 4.3

**Comment by Marcoz08** [comment]
> I got a similar issue when I used IDF branch 4.3.3 so I reverted to 4.2 and build everything now working try it.

Hi, i'm using IDF 4.3, how can i go back to version 4.2?

**Comment by chaitanya-smartrotamac** [comment]
How you installed IDF 4.3 - Windows or linux?
If Windows I used "https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/windows-setup.html#get-started-windows-tools-installer" - IDF Tools installer ,
So I uninstalled it and while installing again it asked 4.3 or 4.2.2 , This time I selected 4.2.2. Done.
If linux no idea, I think you need to checkout 4.2 version branch from git. 
Check getting repositories section in this link "https://github.com/espressif/esp-va-sdk"
Try and let me know.

**Comment by Marcoz08** [comment]
> ¿Cómo instaló IDF 4.3 - Windows o Linux? Si utilicé Windows " https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/windows-setup.html#get-started-windows-tools-installer " - Herramientas IDF instalador, así que lo desinstalé y mientras lo instalaba nuevamente me preguntó 4.3 o 4.2.2, esta vez seleccioné 4.2.2. Hecho. Si linux no tiene idea, creo que debe verificar la rama de la versión 4.2 de git. Consulte la sección de obtención de repositorios en este enlace " https://github.com/espressif/esp-va-sdk " Intente y avíseme.

Thanks, i'm going to try.

**Comment by Marcoz08** [comment]
The problem was solved using IDF 4.2, now the code compiles and flashes successfully.  If someone has the same problem and is using IDF branch 4.3, uninstall it and install version 4.2, to do so use the idf tool.
