### ISSUE TITLE
SPI pins of ZL38063

### ISSUE THREAD

**Issue by robertoimai** [espressif/esp-avs-sdk#17]
Is there a way to change SPI pins of the ZL38063 like we can on the ADF release?
It appears that it is pre-compiled and hard coded.
Also, how do I combine ADF and AVS together?
I would like to both connect to Alexa and also play MP3 files from FATFS and Amazon polly.
It seems to me that I can either do Alexa using AVS-SDK or play MP3 with ADF but not both together as they are independent SDKs.

**Comment by kewalmshah** [comment]
HI @robertoimai, the latest commit provides you the provision to Change SPI pins for ZL38063

**Comment by robertoimai** [comment]
Thanks!
I confirmed this is working.
