### ISSUE TITLE
lyrat alexa

### ISSUE THREAD

**Issue by tcpipchip** [espressif/esp-avs-sdk#171]
I am back after 3 years...

Do you know what means this error ?

I am using the LYRAT WROVER-B

==============================

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x1f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:7328
load:0x40078000,len:13892
ho 0 tail 12 room 4
load:0x40080400,len:5312
entry 0x40080710
I (29) boot: ESP-IDF v4.2.3-112-ga3374b2d2f 2nd stage bootloader
I (29) boot: compile time 16:16:44
I (29) boot: chip revision: 1
I (33) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (40) qio_mode: Enabling default flash chip QIO
I (46) boot.esp32: SPI Speed      : 80MHz
I (50) boot.esp32: SPI Mode       : QIO
I (55) boot.esp32: SPI Flash Size : 4MB
I (59) boot: Enabling RNG early entropy source...
I (65) boot: Partition Table:
I (68) boot: ## Label            Usage          Type ST Offset   Length
I (76) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (83) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (90) boot:  2 factory          factory app      00 00 00010000 00390000
I (98) boot: End of partition table
I (102) boot_comm: chip revision: 1, min. application chip revision: 0
I (109) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x3dd90 (253328) map
E (193) esp_image: invalid segment length 0xc37c9de5
E (193) boot: Factory app partition is not bootable
E (193) boot: No bootable app partitions in the partition table
ets Jun  8 2016 00:22:57

**Comment by tcpipchip** [comment]
i forgot to erase all flash :(

idf.py erase_flash

Now....getting progress :)

btw, i doing all on WSL2

**Comment by tcpipchip** [comment]
working
![image](https://user-images.githubusercontent.com/11488460/178084763-82596d1a-aa83-465d-ab52-754c69381154.png)
Brazil

**Comment by tcpipchip** [comment]
Still working nice!

**Comment by tcpipchip** [comment]
and in portguese :)

**Comment by avsheth** [comment]
That's great to hear :)
Thanks

**Comment by tcpipchip** [comment]
Hi, how can i reset the Lyrat to make a new provisioning ? (on Alexa running on Lyrat)
I want to reset to FACTORY state
Rec?Mode?play ?...etc
Some sequence ?
Thanks!

**Comment by avsheth** [comment]
You'll have to simultaneously press mic mute and TTT buttons for > 10 seconds

**Comment by tcpipchip** [comment]
Hi @avsheth , but my board is this model... :(
![image](https://user-images.githubusercontent.com/11488460/179212956-f0dad54b-3a7c-446f-84c8-340833d5c1ec.png)

**Comment by vikramdattu** [comment]
@tcpipchip please press `Rec` and `Mode` buttons simultaneously for 10 seconds.

**Comment by tcpipchip** [comment]
hi @vikramdattu ok, i will do this afternoon and give you a feedback!

I remember that if did this got GDB message....

Maybe i didnt press "simultaneously"

**Comment by tcpipchip** [comment]
i tested
![image](https://user-images.githubusercontent.com/11488460/179314131-0077c254-ed7d-48f4-be03-aa9eefcb23a8.png)
not solved the problem :(

Anything else ?
