### ISSUE TITLE
xTaskCreateStaticPinnedToCore - assert failed.

### ISSUE THREAD

**Issue by PaulAnurag** [espressif/esp-avs-sdk#173]
Can anyone help me on this. 
Project :esp-va-sdk/examples/amazon_aia

![Issue3](https://user-images.githubusercontent.com/109498417/180360585-a0134ed2-a0c7-4289-a706-7073c2374648.PNG)

**Comment by avsheth** [comment]
Hi @PaulAnurag  I believe this is fixed. Closing this.
