### ISSUE TITLE
How do I change the name of the alexa device?

### ISSUE THREAD

**Issue by robertoimai** [espressif/esp-avs-sdk#23]
How do I change the name of the alexa device after it is provisioned?
It is currently set to ESP AVS Open and I would like to customize it to my own product name and serial number

**Comment by avsheth** [comment]
You can change the name of the device from Alexa developer console but only before you provision the device. Unfortunately I don't think it's possible to change it after you've authenticated your device against your account and a particular security profile.
Go to https://developer.amazon.com/alexa/console/avs/products, sign in with your account, you can either create a new device or modify existing device. While you're provisioning using the app, you can select a particular security profile (which has desired product name).

**Comment by robertoimai** [comment]
When provisioning with the app, it doesn't show me the security profile in my account.
It always shows the esp avs open. Is it because the espressif android apk has that profile locked and I would have to reconcile to be able to change?

Sincerely,
Roberto Imai

Sent from Samsung Note 8
________________________________

**Comment by anujdeshpande** [comment]
Hi @robertoimai - you are right. The APK that we provide has a security profile that one of our engineers has made for making it easy for people to try out the firmware in this repository. Now if you want to change that behaviour, you will have to rebuild the app with your own `Login with Amazon` credentials.

For example, if you want to build the Android app, go to the source in our `versions/avs` branch [here](https://github.com/espressif/esp-idf-provisioning-android/tree/versions/avs). When building the app, you will have to add your API Key from `developer.amazon.com` to the api_key.txt file.

The steps can be found documented in [this](https://github.com/espressif/esp-idf-provisioning-android/blob/versions/avs/README.md) README.

Let me know if you run into any trouble configuring and building
