### ISSUE TITLE
lyratd_msc_alexa_sr例程无法运行

### ISSUE THREAD

**Issue by cc1227858751** [espressif/esp-avs-sdk#24]
rst:0x1 (POWERON_RESET),boot:0x1f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6512
ho 0 tail 12 room 4
load:0x40078000,len:10096
load:0x40080000,len:6700
entry 0x4008034c
[0;32mI (31) boot: ESP-IDF v3.1.1-80-ga18f92b09-dirty 2nd stage bootloader[0m
[0;32mI (31) boot: compile time 10:59:16[0m
[0;32mI (31) boot: Enabling RNG early entropy source...[0m
[0;32mI (37) qio_mode: Enabling default flash chip QIO[0m
[0;32mI (42) boot: SPI Speed      : 40MHz[0m
[0;32mI (46) boot: SPI Mode       : QIO[0m
[0;32mI (50) boot: SPI Flash Size : 1MB[0m
[0;31mE (54) flash_parts: partition 3 invalid - offset 0x20000 size 0x300000 exceeds flash chip size 0x100000[0m
[0;31mE (64) boot: Failed to verify partition table[0m
[0;31mE (69) boot: load partition table error![0m
user code done

**Comment by cc1227858751** [comment]
nfigsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:6512
ho 0 tail 12 room 4
load:0x40078000,len:10096
load:0x40080000,len:6700
entry 0x4008034c
[0;32mI (30) boot: ESP-IDF v3.1.1-80-ga18f92b09-dirty 2nd stage bootloader[0m
[0;32mI (31) boot: compile time 10:59:16[0m
[0;32mI (31) boot: Enabling RNG early entropy source...[0m
[0;32mI (37) qio_mode: Enabling default flash chip QIO[0m
[0;32mI (42) boot: SPI Speed      : 80MHz[0m
[0;32mI (46) boot: SPI Mode       : QIO[0m
[0;32mI (50) boot: SPI Flash Size : 4MB[0m
[0;32mI (54) boot: Partition Table:[0m
[0;32mI (58) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (65) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
[0;32mI (73) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (80) boot:  2 avs              WiFi data        01 02 00010000 00006000[0m
[0;32mI (87) boot:  3 factory          factory app      00 00 00020000 00300000[0m
[0;32mI (95) boot: End of partition table[0m
[0;32mI (99) esp_image: segment 0: paddr=0x00020020 vaddr=0x3f400020 size=0x18546c (1594476) map[0m
[0;32mI (529) esp_image: segment 1: paddr=0x001a5494 vaddr=0x3ffb0000 size=0x04d68 ( 19816) load[0m
[0;32mI (536) esp_image: segment 2: paddr=0x001aa204 vaddr=0x3ffb4d68 size=0x00000 (     0) load[0m
[0;32mI (536) esp_image: segment 3: paddr=0x001aa20c vaddr=0x40080000 size=0x00400 (  1024) load[0m
[0;32mI (546) esp_image: segment 4: paddr=0x001aa614 vaddr=0x40080400 size=0x059fc ( 23036) load[0m
[0;32mI (562) esp_image: segment 5: paddr=0x001b0018 vaddr=0x400d0018 size=0x10944c (1086540) map[0m
[0;32mI (850) esp_image: segment 6: paddr=0x002b946c vaddr=0x40085dfc size=0x14d74 ( 85364) load[0m
[0;32mI (879) esp_image: segment 7: paddr=0x002ce1e8 vaddr=0x400c0000 size=0x00000 (     0) load[0m
[0;32mI (879) esp_image: segment 8: paddr=0x002ce1f0 vaddr=0x50000000 size=0x00000 (     0) load[0m
[0;32mI (901) boot: Loaded app from partition at offset 0x20000[0m
[0;32mI (901) boot: Disabling RNG early entropy source...[0m
[0;32mI (902) spiram: SPI RAM mode: flash 80m sram 80m[0m
[0;32mI (907) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (914) cpu_start: Pro cpu up.[0m
[0;32mI (918) cpu_start: Starting app cpu, entry point is 0x400814f8[0m
[0;32mI (0) cpu_start: App cpu up.[0m
[0;32mI (1424) spiram: SPI SRAM memory test OK[0m
[0;32mI (1425) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1425) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1431) heap_init: At 3FFC0738 len 0001F8C8 (126 KiB): DRAM[0m
[0;32mI (1437) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
[0;32mI (1444) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1450) heap_init: At 4009AB70 len 00005490 (21 KiB): IRAM[0m
[0;32mI (1456) cpu_start: Pro cpu start user code[0m
[0;32mI (1461) spiram: Adding pool of 4096K of external SPI memory to heap allocator[0m
[0;32mI (1469) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
[0;32mI (148) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (149) alexa: ==== Alexa SDK version: v1.0b1-172316 ====[0m
Registering command: mem-dump 
[0;32mI (159) scli: Initialising UART on port 0[0m
[0;32mI (159) uart: queue free spaces: 8[0m

>>Registering command: task-dump 
Registering command: nvs-get 
Registering command: nvs-set 
Registering command: nvs-erase 
Registering command: reboot 
Registering command: heap-trace 
I (179) wifi: wifi driver task: 3ffc84dc, prio:23, stack:3584, core=1
I (189) wifi: wifi firmware version: 38990be
I (189) wifi: config NVS flash: disabled
I (199) wifi: config nano formating: disabled
[0;32mI (199) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (209) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
I (219) wifi: Init dynamic tx buffer num: 32
I (219) wifi: Init data frame dynamic rx buffer num: 32
I (229) wifi: Init management frame dynamic rx buffer num: 32
I (229) wifi: Init static tx buffer num: 32
I (239) wifi: Init static rx buffer size: 1600
I (239) wifi: Init static rx buffer num: 10
I (249) wifi: Init dynamic rx buffer num: 32
[0;32mI (249) conn_mgr: Initialization success[0m
[0;32mI (249) conn_mgr: Received event: 64[0m
[0;32mI (259) softap_sm: SoftAP SSID: ESP-Alexa-8365[0m
 [0;32mI (319) phy: phy_version: 4006, e540b8e, Dec 17 2018, 11:53:06, 0, 0[0m
I (319) wifi: mode : softAP (30:ae:a4:c3:83:65)
I (319) wifi: Init max length of beacon: 752/752
I (319) wifi: Init max length of beacon: 752/752
[0;32mI (329) conn_mgr: Received event: 128[0m
[0;32mI (329) alexa: SOFTAP_STARTED event[0m
[0;32mI (339) protocomm_httpd: Adding endpoint : prov-session[0m
[0;32mI (339) protocomm_httpd: Adding endpoint : avsconfig[0m
[0;32mI (349) protocomm_httpd: Adding endpoint : prov-config[0m

**Comment by cc1227858751** [comment]
修改了下载速度按照指南上面之后log是后面这个。

**Comment by kewalmshah** [comment]
Hi @cc1227858751 From the logs I see that the device is in provisioning mode. Please provision the device using Android app first.

**Comment by avsheth** [comment]
Hi @cc1227858751 
Please check this [link](https://www.youtube.com/watch?v=dTJGbwirTnU&feature=youtu.be) to help you with provisioning
