### ISSUE TITLE
我想通过avs服务实现驱动板子上的io口，也就是在音箱上面装个灯，请问可以实现么，怎么实现

### ISSUE THREAD

**Issue by cc1227858751** [espressif/esp-avs-sdk#25]
就是一个音箱灯，音箱上面带一个灯，请问能实现么，

**Comment by cc1227858751** [comment]
> Hi @cc1227858751
> If I understand correctly, you want to create Alexa-enabled lamp. For that, you need to use aws-iot (please see lyratd_msc_alexa_sr example in the SDK to know how to initialise aws-iot and publish/subscribe to a particular MQTT topic).
> You'll also need to create either a custom or a smart home Alexa skill, which will publish to the topic you would have subscribed above.
> Please refer to below links to know how to build a smart home skill
> https://developer.amazon.com/docs/smarthome/steps-to-build-a-smart-home-skill.html
> https://github.com/alexa/alexa-smarthome/wiki/Build-a-Working-Smart-Home-Skill-in-15-Minutes

感谢您及时回复，我想不通通过alexa来控制我设备的音量这个流程，通过云端来控制设备的状态是怎么实现的呢，我们能不能自己定义云端来改变设备状态呢？

**Comment by anujdeshpande** [comment]
Hi @cc1227858751 
To control the volume of an ESP32 running Alexa or any Alexa device - you have to say `Alexa increase volume` or `Alexa set the volume to 8` or something similar. This sends your query to Alexa Voice Service and the ESP32 device will receive a response directive which will increase the volume.

If you want to control the device remotely, for example if you want to use it as table lamp + Alexa, you will have to add a separate cloud connectivity bit to the firmware examples that you find in this repo. For example, you can use the `aws-iot` examples that can be found [here](https://github.com/espressif/esp-idf/tree/master/examples/protocols/aws_iot) in ESP-IDF. 
ESP AVS SDK is based on top of ESP-IDF so all the functionality of ESP-IDF is supported in the examples that are present in this GitHub repository.
After that you can write an [Alexa Smart Home Skill](https://developer.amazon.com/docs/smarthome/understand-the-smart-home-skill-api.html) that will toggle the state of your Lamp.

**Comment by cc1227858751** [comment]
> Hi @cc1227858751
> To control the volume of an ESP32 running Alexa or any Alexa device - you have to say `Alexa increase volume` or `Alexa set the volume to 8` or something similar. This sends your query to Alexa Voice Service and the ESP32 device will receive a response directive which will increase the volume.
> 
> If you want to control the device remotely, for example if you want to use it as table lamp + Alexa, you will have to add a separate cloud connectivity bit - please check the example [lyrat_alexa_sr](https://github.com/espressif/esp-avs-sdk/tree/master/examples/lyrat_alexa_sr) in this repo. It has an optional AWS IoT component.
> After that you can write an [Alexa Smart Home Skill](https://developer.amazon.com/docs/smarthome/understand-the-smart-home-skill-api.html) that will toggle the state of your Lamp.

十分感谢您的及时回复，意思就是alexa和台灯可以是一个物品，这样做是可以实现的对吧。
