### ISSUE TITLE
这个例程经常连接wifi后崩溃自动复位

### ISSUE THREAD

**Issue by ZKL11G** [espressif/esp-avs-sdk#27]

**Comment by ZKL11G** [comment]
rst:0x1 (POWERON_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6512
ho 0 tail 12 room 4
load:0x40078000,len:10096
load:0x40080000,len:6700
entry 0x4008034c
[0;32mI (31) boot: ESP-IDF v3.1.1-80-ga18f92b09-dirty 2nd stage bootloader[0m
[0;32mI (31) boot: compile time 15:38:39[0m
[0;32mI (35) boot: Enabling RNG early entropy source...[0m
[0;32mI (37) qio_mode: Enabling QIO for flash chip GD[0m
[0;32mI (42) boot: SPI Speed      : 40MHz[0m
[0;32mI (46) boot: SPI Mode       : QIO[0m
[0;32mI (50) boot: SPI Flash Size : 4MB[0m
[0;32mI (55) boot: Partition Table:[0m
[0;32mI (58) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (65) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
[0;32mI (73) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (80) boot:  2 avs              WiFi data        01 02 00010000 00006000[0m
[0;32mI (88) boot:  3 factory          factory app      00 00 00020000 00300000[0m
[0;32mI (95) boot: End of partition table[0m
[0;32mI (99) esp_image: segment 0: paddr=0x00020020 vaddr=0x3f400020 size=0x167240 (1471040) map[0m
[0;32mI (545) esp_image: segment 1: paddr=0x00187268 vaddr=0x3ffb0000 size=0x04e4c ( 20044) load[0m
[0;32mI (552) esp_image: segment 2: paddr=0x0018c0bc vaddr=0x3ffb4e4c size=0x00000 (     0) load[0m
[0;32mI (553) esp_image: segment 3: paddr=0x0018c0c4 vaddr=0x40080000 size=0x00400 (  1024) load[0m
[0;32mI (561) esp_image: segment 4: paddr=0x0018c4cc vaddr=0x40080400 size=0x03b44 ( 15172) load[0m
[0;32mI (576) esp_image: segment 5: paddr=0x00190018 vaddr=0x400d0018 size=0x10a2fc (1090300) map[0m
[0;32mI (903) esp_image: segment 6: paddr=0x0029a31c vaddr=0x40083f44 size=0x15f1c ( 89884) load[0m
[0;32mI (936) esp_image: segment 7: paddr=0x002b0240 vaddr=0x400c0000 size=0x00000 (     0) load[0m
[0;32mI (936) esp_image: segment 8: paddr=0x002b0248 vaddr=0x50000000 size=0x00000 (     0) load[0m
[0;32mI (958) boot: Loaded app from partition at offset 0x20000[0m
[0;32mI (958) boot: Disabling RNG early entropy source...[0m
[0;32mI (959) spiram: SPI RAM mode: flash 80m sram 80m[0m
[0;32mI (964) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (971) cpu_start: Pro cpu up.[0m
[0;32mI (974) cpu_start: Starting app cpu, entry point is 0x400814c8[0m
[0;32mI (0) cpu_start: App cpu up.[0m
[0;32mI (1481) spiram: SPI SRAM memory test OK[0m
[0;32mI (1481) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1482) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1488) heap_init: At 3FFC07F0 len 0001F810 (126 KiB): DRAM[0m
[0;32mI (1494) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
[0;32mI (1500) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1507) heap_init: At 40099E60 len 000061A0 (24 KiB): IRAM[0m
[0;32mI (1513) cpu_start: Pro cpu start user code[0m
[0;32mI (1518) spiram: Adding pool of 4096K of external SPI memory to heap allocator[0m
[0;32mI (1526) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
[0;32mI (205) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (205) alexa: ==== Alexa SDK version: v1.0b1-172316 ====[0m
Registering command: mem-dump 
[0;32mI (255) scli: Initialising UART on port 0[0m
[0;32mI (255) uart: queue free spaces: 8[0m

>>Registering command: task-dump 
Registering command: nvs-get 
Registering command: nvs-set 
Registering command: nvs-erase 
Registering command: reboot 
Registering command: heap-trace 
I (275) wifi: wifi driver task: 3ffc8594, prio:23, stack:3584, core=1
I (275) wifi: wifi firmware version: 38990be
I (285) wifi: config NVS flash: disabled
I (285) wifi: config nano formating: disabled
[0;32mI (285) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (295) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
I (305) wifi: Init dynamic tx buffer num: 32
I (315) wifi: Init data frame dynamic rx buffer num: 32
I (315) wifi: Init management frame dynamic rx buffer num: 32
I (325) wifi: Init static tx buffer num: 32
I (325) wifi: Init static rx buffer size: 1600
I (335) wifi: Init static rx buffer num: 10
I (335) wifi: Init dynamic rx buffer num: 32
[0;32mI (335) conn_mgr: Initialization success[0m
[0;32mI (345) conn_mgr: Received event: 0[0m
[0;32mI (345) sm_sta: In station start[0m
[0;32mI (355) sm_sta: Connecting to SSID: QJ_YJS[0m
 [0;32mI (405) phy: phy_version: 4006, e540b8e, Dec 17 2018, 11:53:06, 0, 0[0m
I (405) wifi: mode : sta (24:0a:c4:9c:aa:48)
[0;32mI (405) conn_mgr: SYSTEM_EVENT_STA_START[0m
[0;32mI (415) conn_mgr: Received event: 128[0m
I (1625) wifi: new:<10,0>, old:<1,0>, ap:<255,255>, sta:<10,0>, prof:1
I (2375) wifi: state: init -> auth (b0)
I (2415) wifi: state: auth -> assoc (0)
I (2435) wifi: state: assoc -> run (10)
I (2565) wifi: connected with QJ_YJS, channel 10, bssid = 34:ce:00:37:6b:be
I (2565) wifi: pm start, type: 1

[0;32mI (2565) conn_mgr: SYSTEM_EVENT_STA_CONNECTED[0m
[0;32mI (2565) conn_mgr: Received event: 128[0m
[0;32mI (2575) alexa: got station connected event[0m
[0;32mI (3775) event: sta ip: 192.168.31.211, mask: 255.255.255.0, gw: 192.168.31.1[0m
[0;32mI (3775) conn_mgr: SYSTEM_EVENT_STA_GOT_IP[0m
[0;32mI (3775) conn_mgr: got ip:192.168.31.211[0m
[0;32mI (3775) conn_mgr: Received event: 128[0m
[0;32mI (3785) alexa: got IPv4:192.168.31.211[0m
[0;32mI (3785) I2S: DMA Malloc info, datalen=blocksize=600, dma_buf_count=3[0m
[0;32mI (3795) I2S: DMA Malloc info, datalen=blocksize=600, dma_buf_count=3[0m
[0;32mI (3795) I2S: PLL_D2: Req RATE: 16000, real rate: 16025.000, BITS: 16, CLKM: 39, BCK: 8, MCLK: 4096000.000, SCLK: 512800.000000, diva: 64, divb: 4[0m
[0;32mI (3815) gpio: GPIO[22]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:0 [0m
[0;32mI (3825) gpio: GPIO[19]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:0 [0m
[0;32mI (3835) UI_LED: LED initialized[0m
[0;32mI (3835) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:1 [0m
[0;32mI (3845) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:3 [0m
[0;32mI (3855) gpio: GPIO[21]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
[0;32mI (3885) dsp: Created I2S audio stream[0m
[0;32mI (3885) audio_stream: Starting i2s_reader stream[0m
Starting audio stream i2s_reader
[0;33mW (3925) I2S: I2S driver already installed[0m
.......................Init i2s stream...............
[0;32mI (3925) audio_stream: Stream i2s_reader Event Started[0m
[0;32mI (3935) dsp: Reader stream event 2[0m
Stopping audio stream i2s_reader
[0;32mI (3945) audio_stream: Stream i2s_reader Event Stopped[0m
[0;32mI (3945) dsp: Reader stream event 3[0m
Generated stopped event for stream i2s_reader
[0;32mI (3955) I2S: PLL_D2: Req RATE: 48000, real rate: 48076.000, BITS: 16, CLKM: 13, BCK: 8, MCLK: 12292917.167, SCLK: 1538432.000000, diva: 64, divb: 1[0m
Starting audio stream i2s_reader
[0;33mW (3975) I2S: I2S driver already installed[0m
.......................Init i2s stream...............
[0;32mI (3975) audio_stream: Stream i2s_reader Event Started[0m
[0;32mI (3985) dsp: Reader stream event 2[0m
[0;32mI (3995) [alexa]: Waiting for time to be updated[0m
[0;32mI (10335) [alexa]: Done getting current time: 1546045050[0m
[0;32mI (10355) [tls_certification]: Done setting global CA store[0m
[0;32mI (10355) audio_stream: Starting playback_writer stream[0m
Starting audio stream playback_writer
[0;32mI (10355) audio_stream: Stream playback_writer Event Started[0m
[0;32mI (10395) LYRAT_CB: Current mode is: 8[0m
[0;32mI (10395) [dialog]: Entering ALEXA_IDLE[0m
[0;31mE (10395) avs-nvs-util: Error opening avs namespace![0m
[0;32mI (10395) [speaker]: Using default volume[0m
[0;32mI (10405) LYRAT_CB: Volume changed to 40[0m
[0;32mI (10405) auth-delegate-config: No NVS partition initialised[0m
[0;31mE (10415) auth-delegate-config: No AVS static config partition found[0m
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x40098d9d  PS      : 0x00060830  A0      : 0x800dbdaa  A1      : 0x3f821610  
A2      : 0x00000000  A3      : 0xfffffffc  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3f8218e0  
A10     : 0x00000003  A11     : 0x00060823  A12     : 0x00060820  A13     : 0x3f8222a0  
A14     : 0x00000000  A15     : 0x00000080  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x40098d9d  LEND    : 0x40098dad  LCOUNT  : 0xffffffff  

Backtrace: 0x40098d9d:0x3f821610

Rebooting...
ets Jun  8 201

**Comment by ZKL11G** [comment]
板子是lyrat 4.3，例程是lyrat_alexa_sr

**Comment by avsheth** [comment]
Hi @ZKL11G This occurs when the device is unable to find any Amazon tokens in NVS. To get rid of this you need to reset your device to factory mode and do provisioning using Android/iOS app.

P.S:  git pull latest changes, since it would allow you to use reset-to-factory push button when you hit this error. Otherwise you can also perform reset-to-factory using either esptool_py (erase_region 0x9000 0x6000) if you are using CLI,  or windows flasher tool.

**Comment by ZKL11G** [comment]
> Hi @ZKL11G This occurs when the device is unable to find any Amazon tokens in NVS. To get rid of this you need to reset your device to factory mode and do provisioning using Android/iOS app.
> 
> P.S: git pull latest changes, since it would allow you to use reset-to-factory push button when you hit this error. Otherwise you can also perform reset-to-factory using either esptool_py (erase_region 0x9000 0x6000) if you are using CLI, or windows flasher tool.

rst:0x1 (POWERON_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6512
ho 0 tail 12 room 4
load:0x40078000,len:10096
load:0x40080000,len:6700
entry 0x4008034c
[0;32mI (31) boot: ESP-IDF v3.1.1-80-ga18f92b09-dirty 2nd stage bootloader[0m
[0;32mI (31) boot: compile time 11:22:22[0m
[0;32mI (33) boot: Enabling RNG early entropy source...[0m
[0;32mI (37) qio_mode: Enabling QIO for flash chip GD[0m
[0;32mI (42) boot: SPI Speed      : 40MHz[0m
[0;32mI (47) boot: SPI Mode       : QIO[0m
[0;32mI (51) boot: SPI Flash Size : 4MB[0m
[0;32mI (55) boot: Partition Table:[0m
[0;32mI (58) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (66) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
[0;32mI (73) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (80) boot:  2 factory          factory app      00 00 00010000 00300000[0m
[0;32mI (88) boot: End of partition table[0m
[0;31mE (92) esp_image: image at 0x10000 has invalid magic byte[0m
[0;33mW (98) esp_image: image at 0x10000 has invalid SPI mode 255[0m
[0;33mW (104) esp_image: image at 0x10000 has invalid SPI size 15[0m
[0;31mE (111) boot: Factory app partition is not bootable[0m
[0;31mE (116) boot: No bootable app partitions in the partition table[0m
user code done

修改之后log如下，还是没法配网

**Comment by ZKL11G** [comment]
> Hi @ZKL11G This occurs when the device is unable to find any Amazon tokens in NVS. To get rid of this you need to reset your device to factory mode and do provisioning using Android/iOS app.
> 
> P.S: git pull latest changes, since it would allow you to use reset-to-factory push button when you hit this error. Otherwise you can also perform reset-to-factory using either esptool_py (erase_region 0x9000 0x6000) if you are using CLI, or windows flasher tool.

配网成功后，连接aws失败，这是log

[0;31mE (67242) [auth-delegate]: Failed to connect to Auth URL "https://api.amazon.com/auth/O2/token"[0m
[0;32mI (67722) conn_mgr_prov: Stopping provisioning[0m
[0;31mE (67752) [auth-delegate]: Authentication attempt failed...retrying ![0m
[0;31mE (67752) [auth-delegate]: Please check connectivity and/or credentials[0m
[0;31mE (67752) [auth-delegate]: In case of authentication failure try resetting the device to factory mode and restart provisioning[0m

**Comment by ZKL11G** [comment]
rst:0xc (SW_CPU_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6512
ho 0 tail 12 room 4
load:0x40078000,len:10096
load:0x40080000,len:6700
entry 0x4008034c
[0;32mI (31) boot: ESP-IDF v3.1.1-80-ga18f92b09-dirty 2nd stage bootloader[0m
[0;32mI (31) boot: compile time 11:22:22[0m
[0;32mI (33) boot: Enabling RNG early entropy source...[0m
[0;32mI (37) qio_mode: Enabling QIO for flash chip GD[0m
[0;32mI (42) boot: SPI Speed      : 40MHz[0m
[0;32mI (47) boot: SPI Mode       : QIO[0m
[0;32mI (51) boot: SPI Flash Size : 4MB[0m
[0;32mI (55) boot: Partition Table:[0m
[0;32mI (58) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (65) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
[0;32mI (73) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (80) boot:  2 factory          factory app      00 00 00010000 00300000[0m
[0;32mI (88) boot: End of partition table[0m
[0;32mI (92) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x1681ac (1474988) map[0m
[0;32mI (539) esp_image: segment 1: paddr=0x001781d4 vaddr=0x3ffb0000 size=0x04f00 ( 20224) load[0m
[0;32mI (546) esp_image: segment 2: paddr=0x0017d0dc vaddr=0x3ffb4f00 size=0x00000 (     0) load[0m
[0;32mI (547) esp_image: segment 3: paddr=0x0017d0e4 vaddr=0x40080000 size=0x00400 (  1024) load[0m
[0;32mI (555) esp_image: segment 4: paddr=0x0017d4ec vaddr=0x40080400 size=0x02b24 ( 11044) load[0m
[0;32mI (568) esp_image: segment 5: paddr=0x00180018 vaddr=0x400d0018 size=0x10af94 (1093524) map[0m
[0;32mI (898) esp_image: segment 6: paddr=0x0028afb4 vaddr=0x40082f24 size=0x16f80 ( 94080) load[0m
[0;32mI (932) esp_image: segment 7: paddr=0x002a1f3c vaddr=0x400c0000 size=0x00000 (     0) load[0m
[0;32mI (932) esp_image: segment 8: paddr=0x002a1f44 vaddr=0x50000000 size=0x00000 (     0) load[0m
[0;32mI (954) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (954) boot: Disabling RNG early entropy source...[0m
[0;32mI (955) spiram: SPI RAM mode: flash 80m sram 80m[0m
[0;32mI (960) spiram: PSRAM initialized, cache is in low/high (2-core) mode.[0m
[0;32mI (967) cpu_start: Pro cpu up.[0m
[0;32mI (971) cpu_start: Starting app cpu, entry point is 0x400814cc[0m
[0;32mI (962) cpu_start: App cpu up.[0m
[0;32mI (1477) spiram: SPI SRAM memory test OK[0m
[0;32mI (1478) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (1478) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (1484) heap_init: At 3FFC0860 len 0001F7A0 (125 KiB): DRAM[0m
[0;32mI (1491) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
[0;32mI (1497) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (1503) heap_init: At 40099EA4 len 0000615C (24 KiB): IRAM[0m
[0;32mI (1510) cpu_start: Pro cpu start user code[0m
[0;32mI (1515) spiram: Adding pool of 4096K of external SPI memory to heap allocator[0m
[0;32mI (1523) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m
[0;32mI (201) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
[0;32mI (202) alexa: ==== Alexa SDK version: v1.0b1-177299 ====[0m
Registering command: mem-dump 
[0;32mI (262) scli: Initialising UART on port 0[0m
[0;32mI (262) uart: queue free spaces: 8[0m

>>Registering command: task-dump 
Registering command: nvs-get 
Registering command: nvs-set 
Registering command: nvs-erase 
Registering command: reboot 
Registering command: heap-trace 
Registering command: button 
Registering command: wifi-set
I (282) wifi: wifi driver task: 3ffc8604, prio:23, stack:3584, core=1
I (282) wifi: wifi firmware version: 38990be
I (292) wifi: config NVS flash: enabled
I (292) wifi: config nano formating: disabled
[0;32mI (302) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (312) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
 I (322) wifi: Init dynamic tx buffer num: 32
I (322) wifi: Init data frame dynamic rx buffer num: 32
I (322) wifi: Init management frame dynamic rx buffer num: 32
I (322) wifi: Init static tx buffer num: 32
I (332) wifi: Init static rx buffer size: 1600
I (332) wifi: Init static rx buffer num: 10
I (342) wifi: Init dynamic rx buffer num: 32
[0;32mI (342) alexa: Starting provisioning[0m
[0;33mW (352) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration[0m
[0;32mI (512) phy: phy_version: 4006, e540b8e, Dec 17 2018, 11:53:06, 0, 2[0m
I (512) wifi: mode : softAP (24:0a:c4:9c:aa:49)
I (512) wifi: Init max length of beacon: 752/752
I (512) wifi: Init max length of beacon: 752/752
[0;32mI (512) conn_mgr_prov: Provisioning started with : 
	service name = ESP-Alexa-AA48 
	service key = [0m
I (13662) wifi: new:<1,0>, old:<1,0>, ap:<1,1>, sta:<255,255>, prof:1
I (13662) wifi: station: 70:8a:09:9c:ae:38 join, AID=1, bgn, 20
[0;32mI (13992) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2[0m
[0;32mI (14002) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2[0m
I (23892) wifi: station: 70:8a:09:9c:ae:38 leave, AID = 1, bss_flags is 134243
I (23892) wifi: new:<1,0>, old:<1,0>, ap:<1,1>, sta:<255,255>, prof:1
I (29102) wifi: new:<1,0>, old:<1,0>, ap:<1,1>, sta:<255,255>, prof:1
I (29102) wifi: station: 70:8a:09:9c:ae:38 join, AID=1, bgn, 20
[0;32mI (29562) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2[0m
[0;32mI (29562) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2[0m
I (51002) wifi: station: 70:8a:09:9c:ae:38 leave, AID = 1, bss_flags is 134243
I (51002) wifi: new:<1,0>, old:<1,0>, ap:<1,1>, sta:<255,255>, prof:1
I (55892) wifi: new:<1,0>, old:<1,0>, ap:<1,1>, sta:<255,255>, prof:1
I (55892) wifi: station: 70:8a:09:9c:ae:38 join, AID=1, bgn, 20
[0;32mI (56152) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2[0m
[0;32mI (57112) conn_mgr_prov_handler: WiFi Credentials Received : 
	ssid QJ_YJS 
	password yjs112233[0m
APP Got: ANykCsgEokudUNvTyEap amzn1.application-oa2-client.a5b0d0c6a5f546499d1e5043f3515e6b amzn://com.espressif.provision abcd1234
I (57332) wifi: mode : sta (24:0a:c4:9c:aa:48) + softAP (24:0a:c4:9c:aa:49)
[0;32mI (57332) conn_mgr_prov: STA Start[0m
[0;32mI (57342) conn_mgr_prov_handler: WiFi Credentials Applied[0m
[0;32mI (57412) conn_mgr_prov_handler: Connecting state[0m
I (58772) wifi: switch to channel 7
I (58772) wifi: ap channel adjust o:1,1 n:7,2
I (58772) wifi: new:<7,0>, old:<1,0>, ap:<7,2>, sta:<0,0>, prof:1
I (58772) wifi: new:<7,2>, old:<7,0>, ap:<7,2>, sta:<7,0>, prof:1
I (59532) wifi: state: init -> auth (b0)
I (59572) wifi: state: auth -> assoc (0)
I (59592) wifi: state: assoc -> run (10)
I (59722) wifi: connected with QJ_YJS, channel 7, bssid = 34:ce:00:37:6b:be
I (59722) wifi: pm start, type: 1

[0;32mI (60282) event: sta ip: 192.168.31.211, mask: 255.255.255.0, gw: 192.168.31.1[0m
[0;32mI (60282) conn_mgr_prov: STA Got IP[0m
[0;32mI (60282) alexa: Connected with IP Address:192.168.31.211[0m
[0;32mI (60282) I2S: DMA Malloc info, datalen=blocksize=600, dma_buf_count=3[0m
[0;32mI (60292) I2S: DMA Malloc info, datalen=blocksize=600, dma_buf_count=3[0m
[0;32mI (60302) I2S: PLL_D2: Req RATE: 16000, real rate: 16025.000, BITS: 16, CLKM: 39, BCK: 8, MCLK: 4096000.000, SCLK: 512800.000000, diva: 64, divb: 4[0m
[0;32mI (60312) gpio: GPIO[22]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:0 [0m
[0;32mI (60322) gpio: GPIO[19]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:0 [0m
[0;32mI (60332) UI_LED: LED initialized[0m
[0;32mI (60332) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:1 [0m
[0;32mI (60342) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 [0m
[0;32mI (60352) gpio: GPIO[21]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m
[0;32mI (60382) dsp: Created I2S audio stream[0m
[0;32mI (60382) audio_stream: Starting i2s_reader stream[0m
Starting audio stream i2s_reader
[0;33mW (60422) I2S: I2S driver already installed[0m
.......................Init i2s stream...............
[0;32mI (60422) audio_stream: Stream i2s_reader Event Started[0m
[0;32mI (60432) dsp: Reader stream event 2[0m
Stopping audio stream i2s_reader
[0;32mI (60442) audio_stream: Stream i2s_reader Event Stopped[0m
[0;32mI (60442) dsp: Reader stream event 3[0m
Generated stopped event for stream i2s_reader
[0;32mI (60452) I2S: PLL_D2: Req RATE: 48000, real rate: 48076.000, BITS: 16, CLKM: 13, BCK: 8, MCLK: 12292917.167, SCLK: 1538432.000000, diva: 64, divb: 1[0m
Starting audio stream i2s_reader
[0;33mW (60482) I2S: I2S driver already installed[0m
.......................Init i2s stream...............
[0;32mI (60482) audio_stream: Stream i2s_reader Event Started[0m
[0;32mI (60482) dsp: Reader stream event 2[0m
[0;32mI (60492) [alexa]: Waiting for time to be updated[0m
[0;32mI (60502) [alexa]: Done getting current time: 1546487573[0m
[0;32mI (60552) [tls_certification]: Done setting global CA store[0m
[0;32mI (60552) audio_stream: Starting playback_writer stream[0m
Starting audio stream playback_writer
[0;32mI (60552) audio_stream: Stream playback_writer Event Started[0m
[0;32mI (60592) LYRAT_CB: Current mode is: 8[0m
[0;32mI (60592) [dialog]: Entering ALEXA_IDLE[0m
[0;31mE (60592) avs-nvs-util: Error opening avs namespace![0m
[0;32mI (60592) [speaker]: Using default volume[0m
[0;32mI (60602) LYRAT_CB: Volume changed to 40[0m
[0;32mI (60602) auth-delegate-config: Returning auth delegate companion app configuration[0m
[0;32mI (60612) [auth-delegate]: Auth delegate with comp app ANykCsgEokudUNvTyEap amzn1.application-oa2-client.a5b0d0c6a5f546499d1e5043f3515e6b amzn://com.espressif.provision abcd1234[0m
[0;31mE (60702) esp-tls: Failed to create socket (family 2 socktype 1 protocol 0)[0m
[0;31mE (60702) [auth-delegate]: Failed to connect to Auth URL "https://api.amazon.com/auth/O2/token"[0m
[0;31mE (61212) [auth-delegate]: Authentication attempt failed...retrying ![0m
[0;31mE (61212) [auth-delegate]: Please check connectivity and/or credentials[0m
[0;31mE (61212) [auth-delegate]: In case of authentication failure try resetting the device to factory mode and restart provisioning[0m
[0;31mE (61242) esp-tls: Failed to create socket (family 2 socktype 1 protocol 0)[0m
[0;31mE (61242) [auth-delegate]: Failed to connect to Auth URL "https://api.amazon.com/auth/O2/token"[0m
[0;31mE (61752) [auth-delegate]: Authentication attempt failed...retrying ![0m
[0;31mE (61752) [auth-delegate]: Please check connectivity and/or credentials[0m
[0;31mE (61752) [auth-delegate]: In case of authentication failure try resetting the device to factory mode and restart provisioning[0m
[0;31mE (61782) esp-tls: Failed to create socket (family 2 socktype 1 protocol 0)[0m

**Comment by ZKL11G** [comment]
[0;32mI (253372) subpub: Stack remaining for task 'aws_iot_task' is 1780 bytes[0m
[0;32mI (254472) subpub: Stack remaining for task 'aws_iot_task' is 1780 bytes[0m
[0;32mI (255572) subpub: Stack remaining for task 'aws_iot_task' is 1780 bytes[0m
[0;32mI (256672) subpub: Stack remaining for task 'aws_iot_task' is 1780 bytes[0m
[0;32mI (257772) subpub: Stack remaining for task 'aws_iot_task' is 1780 bytes[0m
[0;32mI (258872) subpub: Stack remaining for task 'aws_iot_task' is 1780 bytes[0m
[0;32mI (259972) subpub: Stack remaining for task 'aws_iot_task' is 1780 bytes[0m
[0;32mI (261072) subpub: Stack remaining for task 'aws_iot_task' is 1780 bytes[0m
[0;32mI (262172) subpub: Stack remaining for task 'aws_iot_task' is 1780 bytes[0m
