### ISSUE TITLE
Android app APK link is brokken

### ISSUE THREAD

**Issue by hehopmajieh** [espressif/esp-avs-sdk#3]
Android app APK link is broken 
https://github.com/uploads/ad96140f82f02d102b2a65becef8b000/esp-prov-v2.apk

**Comment by avsheth** [comment]
Hi @hehopmajieh Thanks for pointing it out. I have moved the location of the app to Releases. You can download the same from there. I'll update the document.

**Comment by hehopmajieh** [comment]
Hi @avsheth , thank you for fast answer.
