### ISSUE TITLE
ESP32LyraTDMSC example

### ISSUE THREAD

**Issue by batzorigt** [espressif/esp-avs-sdk#4]
I downloaded and built from the example source code for ESP32LyraT.
And I flashed into ESP32LyraTDMSC. But, it does not work on ESP32LyraTDMSC.
I need example source code for ESP32LyraTDMSC.
Is it possible?

**Comment by kewalmshah** [comment]
@batzorigt We will soon have a release and example code to support ESP32LyraTD-MSC as well. Thanks

**Comment by kewalmshah** [comment]
@batzorigt In the meanwhile If you have the MSC firmware, you can write your own application using current example codes as a reference

**Comment by batzorigt** [comment]
> @batzorigt In the meanwhile If you have the MSC firmware, you can write your own application using current example codes as a reference

How can I do it? I downloaded the firmware from https://espressif.github.io/esp-avs-sdk/
It works well but It is only binary.

**Comment by kewalmshah** [comment]
@batzorigt I thought you had the firmware that goes to the Microsemi DSP on board. We are already in the process of releasing support for LyraTD-MSC.

**Comment by kewalmshah** [comment]
@batzorigt We have released support for LyraTD-MSC board. Please take a look. Thanks

**Comment by ameyinamdar** [comment]
Closing the issue as the LyraTD-MSC support is now available.
