### ISSUE TITLE
No reaction when you press the button "Rec"

### ISSUE THREAD

**Issue by chen-zifeng** [espressif/esp-avs-sdk#5]
log:
I (0) cpu_start: App cpu up.
I (1325) spiram: SPI SRAM memory test OK
I (1325) heap_init: Initializing. RAM available for dynamic allocation:
I (1326) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1332) heap_init: At 3FFBF248 len 00020DB8 (131 KiB): DRAM
I (1338) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (1345) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1351) heap_init: At 400998E8 len 00006718 (25 KiB): IRAM
I (1357) cpu_start: Pro cpu start user code
I (1362) spiram: Adding pool of 4096K of external SPI memory to heap allocator
I (1370) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (49) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (49) alexa: ==== Alexa SDK version: v1.0b1-163199 ====
Registering command: mem-dump 
I (69) scli: Initialising UART on port 0
I (69) uart: queue free spaces: 8
>> Registering command: task-dump 
Registering command: nvs-get 
Registering command: nvs-set 
Registering command: heap-trace 
I (89) wifi: wifi driver task: 3ffc6fec, prio:23, stack:3584, core=0
I (89) wifi: wifi firmware version: 633012a
I (89) wifi: config NVS flash: disabled
I (99) wifi: config nano formating: disabled
I (99) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (109) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (119) wifi: Init dynamic tx buffer num: 32
I (129) wifi: Init data frame dynamic rx buffer num: 26
I (129) wifi: Init management frame dynamic rx buffer num: 26
I (139) wifi: Init static tx buffer num: 26
I (139) wifi: Init static rx buffer size: 1600
I (139) wifi: Init static rx buffer num: 10
I (149) wifi: Init dynamic rx buffer num: 26
I (149) conn_mgr: Initialization success
I (159) conn_mgr: Received event: 64
I (159) softap_sm: SoftAP SSID: ESP-Alexa-4d01
I (219) phy: phy_version: 3960, 5211945, Jul 18 2018, 10:40:07, 0, 0
I (219) wifi: mode : softAP (80:7d:3a:e1:4d:01)
I (229) conn_mgr: Received event: 128
I (229) alexa: SOFTAP_STARTED event
I (229) protocomm_httpd: Adding endpoint : prov-session
I (239) protocomm_httpd: Adding endpoint : avsconfig
I (239) protocomm_httpd: Adding endpoint : prov-config
I (4979) wifi: n:1 0, o:1 0, ap:1 1, sta:255 255, prof:1
I (4979) wifi: station: 9c:e8:2b:67:ea:b9 join, AID=1, bgn, 20
I (4979) conn_mgr: Received event: 128
I (5099) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2
I (5099) conn_mgr: Received event: 128

**Comment by avsheth** [comment]
Hi @chen-zifeng 
Device is still in provisioning mode. Rec button will be effective as soon as device is connected to an AP.
Please provision the device using Android app first.

**Comment by TraDao** [comment]
Hi @avsheth I have the same issue as @chen-zifeng . (same message in console)

I used Espressif app on android. The app says: "To provision your new device, please make sure that your device is turned on and the Wifi symbol blinks green". But the Wifi symbol green led does not blink, it is off. There is no way to set it blink. 

I tried to go to next step: connect to ESP-Alexa-xxx (without green led blinking). The board stays in provisioning mode forever. (it show same message as @chen-zifeng 's)

**Comment by avsheth** [comment]
Hi @TraDao 
After connecting to ESP-Alexa-xxx, please go back to the App, where you'll see "Provision Network" button enabled, clicking on which will give you couple of text boxes for entering SSID and passphrase of the network you wish to connect to (for now you have to enter SSID and passphrase manually). Once the device is connected to the AP you can start a conversation with Alexa

**Comment by TraDao** [comment]
Hi @avsheth 
It works well now.
Notes: I go back to the App, but don't see "Provision Network". Still see "Connect". Then, I installed the app on another android phone, and login with another amazon account. Setting up successfully on this phone. I can run the demo now.
(First failed phone is Google Pixel, Second phone is J7 pro)
Thank you very much!

**Comment by avsheth** [comment]
Hi Thanks for letting us know. We will check if there's any issue with Google Pixel.

**Comment by xiaoseyihe** [comment]
hi @avsheth 感谢你的回答，我参考“After connecting to ESP-Alexa-xxx, please go back to the App, where you'll see "Provision Network" button enabled, clicking on which will give you couple of text boxes for entering SSID and passphrase of the network you wish to connect to (for now you have to enter SSID and passphrase manually). Once the device is connected to the AP you can start a conversation with Alexa”进行设置，设备连接WiFi，退出ESP-Alexa-xxx，
rst:0x10 (RTCWDT_RTC_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:6200
load:0x40078000,len:9940
load:0x40080000,len:6756
entry 0x40080350
I (29) boot: ESP-IDF v3.1-91-gf11ac03-dirty 2nd stage bootloader
I (29) boot: compile time 11:57:34
I (33) boot: Enabling RNG early entropy source...
I (35) qio_mode: Enabling QIO for flash chip GD
I (40) boot: SPI Speed      : 80MHz
I (44) boot: SPI Mode       : QIO
I (48) boot: SPI Flash Size : 4MB
I (52) boot: Partition Table:
I (56) boot: ## Label            Usage          Type ST Offset   Length
I (63) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (71) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (78) boot:  2 avs              WiFi data        01 02 00010000 00006000
I (86) boot:  3 factory          factory app      00 00 00020000 00300000
I (93) boot: End of partition table
I (97) esp_image: segment 0: paddr=0x00020020 vaddr=0x3f400020 size=0x14258c (1320332) map
I (455) esp_image: segment 1: paddr=0x001625b4 vaddr=0x3ffb0000 size=0x05088 ( 20616) load
I (462) esp_image: segment 2: paddr=0x00167644 vaddr=0x3ffb5088 size=0x00000 (     0) load
I (462) esp_image: segment 3: paddr=0x0016764c vaddr=0x40080000 size=0x00400 (  1024) load
I (471) esp_image: segment 4: paddr=0x00167a54 vaddr=0x40080400 size=0x085bc ( 34236) load
I (491) esp_image: segment 5: paddr=0x00170018 vaddr=0x400d0018 size=0xfa1c0 (1024448) map
I (762) esp_image: segment 6: paddr=0x0026a1e0 vaddr=0x400889bc size=0x117b8 ( 71608) load
I (786) esp_image: segment 7: paddr=0x0027b9a0 vaddr=0x400c0000 size=0x00000 (     0) load
I (786) esp_image: segment 8: paddr=0x0027b9a8 vaddr=0x50000000 size=0x00000 (     0) load
I (808) boot: Loaded app from partition at offset 0x20000
I (808) boot: Disabling RNG early entropy source...
I (809) spiram: SPI RAM mode: flash 80m sram 80m
I (814) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (821) cpu_start: Pro cpu up.
I (825) cpu_start: Starting app cpu, entry point is 0x400814bc
I (0) cpu_start: App cpu up.
I (1325) spiram: SPI SRAM memory test OK
I (1325) heap_init: Initializing. RAM available for dynamic allocation:
I (1325) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1331) heap_init: At 3FFBF100 len 00020F00 (131 KiB): DRAM
I (1338) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (1344) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1351) heap_init: At 4009A174 len 00005E8C (23 KiB): IRAM
I (1357) cpu_start: Pro cpu start user code
I (1362) spiram: Adding pool of 4096K of external SPI memory to heap allocator
I (1370) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (48) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (49) alexa: ==== Alexa SDK version: v1.0b1-165973 ====
Registering command: mem-dump 
I (99) scli: Initialising UART on port 0
I (99) uart: queue free spaces: 8

>> Registering command: task-dump 
Registering command: nvs-get 
Registering command: nvs-set 
Registering command: heap-trace 
I (109) wifi: wifi driver task: 3ffcafec, prio:23, stack:3584, core=0
I (109) wifi: wifi firmware version: 75aab56
I (119) wifi: config NVS flash: disabled
I (119) wifi: config nano formating: disabled
I (129) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (139) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (149) wifi: Init dynamic tx buffer num: 32
I (149) wifi: Init data frame dynamic rx buffer num: 32
I (149) wifi: Init management frame dynamic rx buffer num: 32
I (159) wifi: Init static tx buffer num: 32
I (159) wifi: Init static rx buffer size: 1600
I (169) wifi: Init static rx buffer num: 10
I (169) wifi: Init dynamic rx buffer num: 32
I (179) conn_mgr: Initialization success
I (179) conn_mgr: Received event: 64
I (179) softap_sm: SoftAP SSID: ESP-Alexa-4fa1
I (249) phy: phy_version: 4000, b6198fa, Sep  3 2018, 15:11:06, 0, 0
I (249) wifi: mode : softAP (80:7d:3a:e1:4f:a1)
I (249) wifi: Init max length of beacon: 752/752
I (259) wifi: Init max length of beacon: 752/752
I (259) conn_mgr: Received event: 128
I (269) alexa: SOFTAP_STARTED event
I (269) protocomm_httpd: Adding endpoint : prov-session
I (279) protocomm_httpd: Adding endpoint : avsconfig
I (279) protocomm_httpd: Adding endpoint : prov-config
I (64189) wifi: n:1 0, o:1 0, ap:1 1, sta:255 255, prof:1
I (64189) wifi: station: 8c:79:67:c8:70:ab join, AID=1, bgn, 20
I (64189) conn_mgr: Received event: 128
I (64479) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2
I (64479) conn_mgr: Received event: 128
I (102609) wifi: station: 8c:79:67:c8:70:ab leave, AID = 1
I (102609) wifi: n:1 0, o:1 0, ap:1 1, sta:255 255, prof:1
I (102609) conn_mgr: Received event: 128
I (416199) wifi: n:1 0, o:1 0, ap:1 1, sta:255 255, prof:1
I (416199) wifi: station: 8c:79:67:c8:70:ab join, AID=1, bgn, 20
I (416199) conn_mgr: Received event: 128
I (416789) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2
I (416789) conn_mgr: Received event: 128
W (419199) wifi: rx ampdu exist: tid=0 new <ssn=74 win=0> old <ssn=74 win=6>
W (420199) wifi: rx ampdu exist: tid=0 new <ssn=131 win=0> old <ssn=131 win=6>
W (421209) wifi: rx ampdu exist: tid=0 new <ssn=237 win=0> old <ssn=236 win=6>
W (422199) wifi: rx ampdu exist: tid=0 new <ssn=268 win=0> old <ssn=268 win=6>
W (423199) wifi: rx ampdu exist: tid=0 new <ssn=308 win=0> old <ssn=308 win=6>
W (424199) wifi: rx ampdu exist: tid=0 new <ssn=334 win=0> old <ssn=334 win=6>
W (425209) wifi: rx ampdu exist: tid=0 new <ssn=395 win=0> old <ssn=395 win=6>
W (426209) wifi: rx ampdu exist: tid=0 new <ssn=448 win=0> old <ssn=448 win=6>
W (427259) wifi: rx ampdu exist: tid=0 new <ssn=494 win=0> old <ssn=494 win=6>
W (428209) wifi: rx ampdu exist: tid=0 new <ssn=521 win=0> old <ssn=521 win=6>
W (430209) wifi: rx ampdu exist: tid=0 new <ssn=586 win=0> old <ssn=586 win=6>
W (431209) wifi: rx ampdu exist: tid=0 new <ssn=620 win=0> old <ssn=620 win=6>
W (432209) wifi: rx ampdu exist: tid=0 new <ssn=644 win=0> old <ssn=644 win=6>
W (433209) wifi: rx ampdu exist: tid=0 new <ssn=658 win=0> old <ssn=658 win=6>
W (434219) wifi: rx ampdu exist: tid=0 new <ssn=681 win=0> old <ssn=681 win=6>
W (435209) wifi: rx ampdu exist: tid=0 new <ssn=707 win=0> old <ssn=707 win=6>
W (436209) wifi: rx ampdu exist: tid=0 new <ssn=715 win=0> old <ssn=715 win=6>
W (437209) wifi: rx ampdu exist: tid=0 new <ssn=753 win=0> old <ssn=753 win=6>
W (438209) wifi: rx ampdu exist: tid=0 new <ssn=770 win=0> old <ssn=770 win=6>
W (439239) wifi: rx ampdu exist: tid=0 new <ssn=792 win=0> old <ssn=792 win=6>
W (440219) wifi: rx ampdu exist: tid=0 new <ssn=819 win=0> old <ssn=819 win=6>
W (441229) wifi: rx ampdu exist: tid=0 new <ssn=834 win=0> old <ssn=834 win=6>
W (442229) wifi: rx ampdu exist: tid=0 new <ssn=870 win=0> old <ssn=870 win=6>
W (443229) wifi: rx ampdu exist: tid=0 new <ssn=903 win=0> old <ssn=903 win=6>
W (445229) wifi: rx ampdu exist: tid=0 new <ssn=923 win=0> old <ssn=923 win=6>
W (446239) wifi: rx ampdu exist: tid=0 new <ssn=936 win=0> old <ssn=936 win=6>
W (447229) wifi: rx ampdu exist: tid=0 new <ssn=957 win=0> old <ssn=946 win=6>
W (448229) wifi: rx ampdu exist: tid=0 new <ssn=971 win=0> old <ssn=971 win=6>
W (449229) wifi: rx ampdu exist: tid=0 new <ssn=980 win=0> old <ssn=980 win=6>
W (450239) wifi: rx ampdu exist: tid=0 new <ssn=1003 win=0> old <ssn=1003 win=6>
W (451249) wifi: rx ampdu exist: tid=0 new <ssn=1016 win=0> old <ssn=1016 win=6>
W (452259) wifi: rx ampdu exist: tid=0 new <ssn=1039 win=0> old <ssn=1039 win=6>
W (453259) wifi: rx ampdu exist: tid=0 new <ssn=1063 win=0> old <ssn=1063 win=6>
W (454269) wifi: rx ampdu exist: tid=0 new <ssn=1082 win=0> old <ssn=1082 win=6>
W (455259) wifi: rx ampdu exist: tid=0 new <ssn=1125 win=0> old <ssn=1125 win=6>
I (455349) protocomm_httpd: Session ID: 63
I (455569) security1: Device pubkey:
I (455569) security1: 09 dd 62 f8 7e f0 3a ea 39 81 b5 ed 47 82 ef 46 
I (455569) security1: 35 3a cb b8 8c 2b e0 5c 6e 9b 2d 1c c2 0e 82 0e 
I (455569) security1: Client pubkey:
I (455579) security1: 86 8e 4d bf d8 6c 07 27 97 68 35 b0 38 fb 2d 09 
I (455589) security1: 54 cd 4a 89 af 32 fb c8 d1 61 5a 1d f0 ce 20 37 
I (455819) security1: Shared key:
I (455819) security1: c5 18 80 c2 47 98 d0 55 d4 5c b3 1a db 78 4e f4 
I (455819) security1: 3c bb 4f 0e 54 d0 5e 43 21 4b dc 05 28 0a 17 d1 
I (455829) security1: Device random:
I (455829) security1: 3e 58 3b 76 24 10 b6 1f 3b 90 9d 2e 6f b9 31 b7 
I (455839) protocomm_httpd: ADI Done
I (455899) protocomm_httpd: Session ID: 63
I (455899) security1: Client verifier:
I (455899) security1: c5 7e 2a d3 6b c7 1f 0b e7 22 b8 03 92 60 e6 bd 
I (455909) security1: a2 05 6f c6 a3 c0 35 ee 3f 56 59 fb b6 65 5d 9c 
I (455909) security1: Dec Client verifier:
I (455919) security1: 09 dd 62 f8 7e f0 3a ea 39 81 b5 ed 47 82 ef 46 
I (455929) security1: 35 3a cb b8 8c 2b e0 5c 6e 9b 2d 1c c2 0e 82 0e 
I (455929) security1: Device verify data:
I (455939) security1: 05 61 d7 35 94 22 36 16 51 da 90 5d d7 ab 26 ca 
I (455939) security1: ea 02 8f e3 8a bd 10 2c 33 b9 e2 d1 8c 84 22 5f 
I (455949) protocomm_httpd: ADI Done
I (456099) protocomm_httpd: Session ID: 63
I (456099) wifi_hdlr: Creds received belkin.36f7 64c886fd
I (456109) protocomm_httpd: ADI Done
I (456189) protocomm_httpd: Session ID: 63
APP Got: ANMjgBHkgctVDuEpQkZQ amzn1.application-oa2-client.a5b0d0c6a5f546499d1e5043f3515e6b amzn://com.espressif.provision abcd1234
I (456199) protocomm_httpd: ADI Done
W (456259) wifi: rx ampdu exist: tid=0 new <ssn=1156 win=0> old <ssn=1156 win=6>
I (456379) protocomm_httpd: Session ID: 63
I (456389) conn_mgr: Received event: 66
I (456389) alexa: got station network credential recieved event
I (456389) conn_mgr: Received event: 0
I (456389) sm_sta: In station start
I (456399) protocomm_httpd: ADI Done
I (456399) sm_sta: Connecting to SSID: belkin.36f7
I (456409) wifi: mode : sta (80:7d:3a:e1:4f:a0) + softAP (80:7d:3a:e1:4f:a1)
I (456419) conn_mgr: SYSTEM_EVENT_STA_START
I (456419) conn_mgr: Received event: 128
I (456469) protocomm_httpd: Session ID: 63
Connecting state
I (456469) protocomm_httpd: ADI Done
I (456699) wifi: n:1 1, o:1 0, ap:1 1, sta:1 1, prof:1
I (457449) wifi: state: init -> auth (b0)
I (457449) wifi: state: auth -> assoc (0)
I (457479) wifi: state: assoc -> run (10)
I (457659) wifi: connected with belkin.36f7, channel 1
I (457659) wifi: pm start, type: 1

I (457659) conn_mgr: SYSTEM_EVENT_STA_CONNECTED
I (457659) conn_mgr: Received event: 128
I (457659) alexa: got station connected event
W (458259) wifi: rx ampdu exist: tid=0 new <ssn=1232 win=0> old <ssn=1226 win=6>
I (459109) event: sta ip: 192.168.2.8, mask: 255.255.255.0, gw: 192.168.2.1
I (459109) conn_mgr: SYSTEM_EVENT_STA_GOT_IP
I (459109) conn_mgr: got ip:192.168.2.8
I (459109) conn_mgr: Received event: 128
I (459119) alexa: got IPv4:192.168.2.8
W (459269) wifi: rx ampdu exist: tid=0 new <ssn=1254 win=0> old <ssn=1248 win=6>
W (460269) wifi: rx ampdu exist: tid=0 new <ssn=1296 win=0> old <ssn=1296 win=6>
W (461269) wifi: rx ampdu exist: tid=0 new <ssn=1329 win=0> old <ssn=1329 win=6>
I (461719) protocomm_httpd: Session ID: 63
Connected state
I (461719) protocomm_httpd: ADI Done
W (462269) wifi: rx ampdu exist: tid=0 new <ssn=1357 win=0> old <ssn=1357 win=6>
W (463269) wifi: rx ampdu exist: tid=0 new <ssn=1379 win=0> old <ssn=1379 win=6>
W (464279) wifi: rx ampdu exist: tid=0 new <ssn=1397 win=0> old <ssn=1397 win=6>
W (465279) wifi: rx ampdu exist: tid=0 new <ssn=1428 win=0> old <ssn=1419 win=6>
W (466279) wifi: rx ampdu exist: tid=0 new <ssn=1447 win=0> old <ssn=1447 win=6>
W (467279) wifi: rx ampdu exist: tid=0 new <ssn=1482 win=0> old <ssn=1483 win=6>
W (468289) wifi: rx ampdu exist: tid=0 new <ssn=1516 win=0> old <ssn=1516 win=6>
W (469289) wifi: rx ampdu exist: tid=0 new <ssn=1550 win=0> old <ssn=1549 win=6>
W (470299) wifi: rx ampdu exist: tid=0 new <ssn=1582 win=0> old <ssn=1581 win=6>
W (471299) wifi: rx ampdu exist: tid=0 new <ssn=1603 win=0> old <ssn=1603 win=6>
W (472299) wifi: rx ampdu exist: tid=0 new <ssn=1631 win=0> old <ssn=1631 win=6>
W (473299) wifi: rx ampdu exist: tid=0 new <ssn=1663 win=0> old <ssn=1663 win=6>
I (474119) wifi: station: 8c:79:67:c8:70:ab leave, AID = 1
I (474119) wifi: n:1 1, o:1 1, ap:1 1, sta:1 1, prof:1
I (474119) wifi: mode : sta (80:7d:3a:e1:4f:a0)
I (474119) conn_mgr: Received event: 65
W (474129) httpd_txrx: httpd_default_recv: error in recv = 113
I (474129) protocomm_httpd: Removing endpoint : prov-config
W (474139) httpd_txrx: httpd_resp_send_err: 408 Request Timeout - Server closed this connection
I (474149) protocomm_httpd: Removing endpoint : avsconfig
W (474159) httpd_txrx: httpd_default_send: error in send = 113
I (474159) protocomm_httpd: Removing endpoint : prov-session
I (475169) conn_mgr: Received event: 128
I (475169) conn_mgr: Received event: 128
I (475169) I2S: DMA Malloc info, datalen=blocksize=600, dma_buf_count=3
I (475169) I2S: DMA Malloc info, datalen=blocksize=600, dma_buf_count=3
I (475179) I2S: PLL_D2: Req RATE: 16000, real rate: 16025.000, BITS: 16, CLKM: 39, BCK: 8, MCLK: 4096000.000, SCLK: 512800.000000, diva: 64, divb: 4
I (475189) gpio: GPIO[22]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:0 
I (475199) gpio: GPIO[19]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:0 
I (475209) UI_LED: LED initialized
I (475219) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:1 
I (475219) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:3 
I (475229) gpio: GPIO[21]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (475259) dsp: Created I2S audio stream
I (475259) audio_stream: Starting i2s_reader stream
Starting audio stream i2s_reader
W (475259) I2S: I2S driver already installed
.......................Init i2s stream...............
I (475269) audio_stream: Stream i2s_reader Event Started
I (475279) dsp: Reader stream event 2
speech_recognizer: Ignoring data in idle state
speech_recognizer: Ignoring data in idle state
speech_recognizer: Ignoring data in idle state
Stopping audio stream i2s_reader
speech_recognizer: Ignoring data in idle state
I (475299) audio_stream: Stream i2s_reader Event Stopped
I (475309) dsp: Reader stream event 3
Generated stopped event for stream i2s_reader
I (475319) I2S: PLL_D2: Req RATE: 48000, real rate: 48076.000, BITS: 16, CLKM: 13, BCK: 8, MCLK: 12292917.167, SCLK: 1538432.000000, diva: 64, divb: 1
I (475329) audio_stream: Starting playback_writer stream
Starting audio stream playback_writer
I (475339) audio_stream: Stream playback_writer Event Started
E (475349) avs-nvs-util: Error opening avs namespace!
I (475349) [speaker]: Using default volume
I (475359) LYRAT_CB: Volume changed to 40
I (475359) auth-delegate-config: Returning auth delegate companion app configuration
I (475369) [auth-delegate]: Auth delegate with comp app ANMjgBHkgctVDuEpQkZQ amzn1.application-oa2-client.a5b0d0c6a5f546499d1e5043f3515e6b amzn://com.espressif.provision abcd1234
I (479699) auth-delegate-config: Set client ID amzn1.application-oa2-client.a5b0d0c6a5f546499d1e5043f3515e6b and refresh token Atzr|IwEBINyiji6thlJDhNSMVXaPq7DFszWjuVK9TntaVLGQF-o2G4oCJQSoQYzX2AHESNK5TZ-ubcXahYDBZ7IrvQRdfTm5L9ihKYwbn2pmx3G6vhI78pdZ_NmPjJVDEbDectEDWnOQ9nOB9Gwa8-0fAjUsHA9k-GwlAPMPmNMzw4bPyDKVuLFgKKQwYuMHs8dyS_oYbpcehKrD7jx4eWZ3I6o4AMuKm7y7bHKCO75MSxBfGv7l16YqWKYMmsnarHNcYLv_CHQbNl-8XxMbRp1fbzx6-7LMGpsnVjUQVpKfKv4ZSnN-Js72KG-sqwlHm939d08a8VkMO0wyq3VUaCG9Uw83YBz4Pnd20ctmBV0g1CQen47uR5MrZzwbMYkKpHsngymL5hUxDrLe17bElm_CZX94i6C_eIrngf-h-sdjKGrMioUyrvOgWnIyZCSqzebPF4Y2gv4J5KHwBVhfGaGLHz2OEa-tl3laCARmQ38nQyBcd5GQKoU5QmK6dQk85cHTpVk25SVBR-L8mqWJAwsr5DydWf3Xre7GgESW3fwksg2eplA7iw in NVS successfully
I (479759) [auth-delegate]: Authentication Done !
I (479759) avs-nvs-util: No value set for: cap_version
I (479769) capabilities: capabilities version not found in NVS or version is different

这是怎么回事？谢谢回答
