### ISSUE TITLE
lyrat_alexa 与 lyrat_alexa_sr的区别

### ISSUE THREAD

**Issue by xiaoseyihe** [espressif/esp-avs-sdk#8]
你好，从描述中看到，lyrat_alexa不支持“Alexa”唤醒，只支持按键，lyrat_alexa_sr可以支持“Alexa”唤醒，但是只支持 LyraT v4.1, LyraT v4.2，不支持 LyraT v4.3,是这样的吗？

我目前用的设备是 LyraT v4.3，怎么实现“Alexa”唤醒词唤醒功能？多谢指导

**Comment by avsheth** [comment]
Hi @xiaoseyihe 
Latest release supports wakeword on LyraT v4.3 also.
Thanks for pointing out, will update the README

**Comment by xiaoseyihe** [comment]
@avsheth 感谢您的回答，我烧写lyrat_alexa_sr的版本后，串口打印连接WiFi，为什么指示灯不显示呢？

串口打印如下：
Registering command: task-dump
Registering command: nvs-get
Registering command: nvs-set
Registering command: heap-trace
I (109) wifi: wifi driver task: 3ffcafec, prio:23, stack:3584, core=0
I (109) wifi: wifi firmware version: 75aab56
I (119) wifi: config NVS flash: disabled
I (119) wifi: config nano formating: disabled
I (129) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (139) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (149) wifi: Init dynamic tx buffer num: 32
I (149) wifi: Init data frame dynamic rx buffer num: 32
I (149) wifi: Init management frame dynamic rx buffer num: 32
I (159) wifi: Init static tx buffer num: 32
I (159) wifi: Init static rx buffer size: 1600
I (169) wifi: Init static rx buffer num: 10
I (169) wifi: Init dynamic rx buffer num: 32
I (179) conn_mgr: Initialization success
I (179) conn_mgr: Received event: 64
I (179) softap_sm: SoftAP SSID: ESP-Alexa-4fa1
I (249) phy: phy_version: 4000, b6198fa, Sep 3 2018, 15:11:06, 0, 0
I (249) wifi: mode : softAP (80:7d:3a:e1:4f:a1)
I (249) wifi: Init max length of beacon: 752/752
I (259) wifi: Init max length of beacon: 752/752
I (259) conn_mgr: Received event: 128
I (269) alexa: SOFTAP_STARTED event
I (269) protocomm_httpd: Adding endpoint : prov-session
I (279) protocomm_httpd: Adding endpoint : avsconfig
I (279) protocomm_httpd: Adding endpoint : prov-config
I (64189) wifi: n:1 0, o:1 0, ap:1 1, sta:255 255, prof:1
I (64189) wifi: station: 8c:79:67:c8:70:ab join, AID=1, bgn, 20
I (64189) conn_mgr: Received event: 128
I (64479) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2
I (64479) conn_mgr: Received event: 128
I (102609) wifi: station: 8c:79:67:c8:70:ab leave, AID = 1
I (102609) wifi: n:1 0, o:1 0, ap:1 1, sta:255 255, prof:1
I (102609) conn_mgr: Received event: 128
I (416199) wifi: n:1 0, o:1 0, ap:1 1, sta:255 255, prof:1
I (416199) wifi: station: 8c:79:67:c8:70:ab join, AID=1, bgn, 20
I (416199) conn_mgr: Received event: 128
I (416789) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2
I (416789) conn_mgr: Received event: 128
W (419199) wifi: rx ampdu exist: tid=0 new <ssn=74 win=0> old <ssn=74 win=6>
W (420199) wifi: rx ampdu exist: tid=0 new <ssn=131 win=0> old <ssn=131 win=6>
W (421209) wifi: rx ampdu exist: tid=0 new <ssn=237 win=0> old <ssn=236 win=6>
W (422199) wifi: rx ampdu exist: tid=0 new <ssn=268 win=0> old <ssn=268 win=6>
W (423199) wifi: rx ampdu exist: tid=0 new <ssn=308 win=0> old <ssn=308 win=6>
W (424199) wifi: rx ampdu exist: tid=0 new <ssn=334 win=0> old <ssn=334 win=6>
W (425209) wifi: rx ampdu exist: tid=0 new <ssn=395 win=0> old <ssn=395 win=6>
W (426209) wifi: rx ampdu exist: tid=0 new <ssn=448 win=0> old <ssn=448 win=6>
W (427259) wifi: rx ampdu exist: tid=0 new <ssn=494 win=0> old <ssn=494 win=6>
W (428209) wifi: rx ampdu exist: tid=0 new <ssn=521 win=0> old <ssn=521 win=6>
W (430209) wifi: rx ampdu exist: tid=0 new <ssn=586 win=0> old <ssn=586 win=6>
W (431209) wifi: rx ampdu exist: tid=0 new <ssn=620 win=0> old <ssn=620 win=6>
W (432209) wifi: rx ampdu exist: tid=0 new <ssn=644 win=0> old <ssn=644 win=6>
W (433209) wifi: rx ampdu exist: tid=0 new <ssn=658 win=0> old <ssn=658 win=6>
W (434219) wifi: rx ampdu exist: tid=0 new <ssn=681 win=0> old <ssn=681 win=6>
W (435209) wifi: rx ampdu exist: tid=0 new <ssn=707 win=0> old <ssn=707 win=6>
W (436209) wifi: rx ampdu exist: tid=0 new <ssn=715 win=0> old <ssn=715 win=6>
W (437209) wifi: rx ampdu exist: tid=0 new <ssn=753 win=0> old <ssn=753 win=6>
W (438209) wifi: rx ampdu exist: tid=0 new <ssn=770 win=0> old <ssn=770 win=6>
W (439239) wifi: rx ampdu exist: tid=0 new <ssn=792 win=0> old <ssn=792 win=6>
W (440219) wifi: rx ampdu exist: tid=0 new <ssn=819 win=0> old <ssn=819 win=6>
W (441229) wifi: rx ampdu exist: tid=0 new <ssn=834 win=0> old <ssn=834 win=6>
W (442229) wifi: rx ampdu exist: tid=0 new <ssn=870 win=0> old <ssn=870 win=6>
W (443229) wifi: rx ampdu exist: tid=0 new <ssn=903 win=0> old <ssn=903 win=6>
W (445229) wifi: rx ampdu exist: tid=0 new <ssn=923 win=0> old <ssn=923 win=6>
W (446239) wifi: rx ampdu exist: tid=0 new <ssn=936 win=0> old <ssn=936 win=6>
W (447229) wifi: rx ampdu exist: tid=0 new <ssn=957 win=0> old <ssn=946 win=6>
W (448229) wifi: rx ampdu exist: tid=0 new <ssn=971 win=0> old <ssn=971 win=6>
W (449229) wifi: rx ampdu exist: tid=0 new <ssn=980 win=0> old <ssn=980 win=6>
W (450239) wifi: rx ampdu exist: tid=0 new <ssn=1003 win=0> old <ssn=1003 win=6>
W (451249) wifi: rx ampdu exist: tid=0 new <ssn=1016 win=0> old <ssn=1016 win=6>
W (452259) wifi: rx ampdu exist: tid=0 new <ssn=1039 win=0> old <ssn=1039 win=6>
W (453259) wifi: rx ampdu exist: tid=0 new <ssn=1063 win=0> old <ssn=1063 win=6>
W (454269) wifi: rx ampdu exist: tid=0 new <ssn=1082 win=0> old <ssn=1082 win=6>
W (455259) wifi: rx ampdu exist: tid=0 new <ssn=1125 win=0> old <ssn=1125 win=6>
I (455349) protocomm_httpd: Session ID: 63
I (455569) security1: Device pubkey:
I (455569) security1: 09 dd 62 f8 7e f0 3a ea 39 81 b5 ed 47 82 ef 46
I (455569) security1: 35 3a cb b8 8c 2b e0 5c 6e 9b 2d 1c c2 0e 82 0e
I (455569) security1: Client pubkey:
I (455579) security1: 86 8e 4d bf d8 6c 07 27 97 68 35 b0 38 fb 2d 09
I (455589) security1: 54 cd 4a 89 af 32 fb c8 d1 61 5a 1d f0 ce 20 37
I (455819) security1: Shared key:
I (455819) security1: c5 18 80 c2 47 98 d0 55 d4 5c b3 1a db 78 4e f4
I (455819) security1: 3c bb 4f 0e 54 d0 5e 43 21 4b dc 05 28 0a 17 d1
I (455829) security1: Device random:
I (455829) security1: 3e 58 3b 76 24 10 b6 1f 3b 90 9d 2e 6f b9 31 b7
I (455839) protocomm_httpd: ADI Done
I (455899) protocomm_httpd: Session ID: 63
I (455899) security1: Client verifier:
I (455899) security1: c5 7e 2a d3 6b c7 1f 0b e7 22 b8 03 92 60 e6 bd
I (455909) security1: a2 05 6f c6 a3 c0 35 ee 3f 56 59 fb b6 65 5d 9c
I (455909) security1: Dec Client verifier:
I (455919) security1: 09 dd 62 f8 7e f0 3a ea 39 81 b5 ed 47 82 ef 46
I (455929) security1: 35 3a cb b8 8c 2b e0 5c 6e 9b 2d 1c c2 0e 82 0e
I (455929) security1: Device verify data:
I (455939) security1: 05 61 d7 35 94 22 36 16 51 da 90 5d d7 ab 26 ca
I (455939) security1: ea 02 8f e3 8a bd 10 2c 33 b9 e2 d1 8c 84 22 5f
I (455949) protocomm_httpd: ADI Done
I (456099) protocomm_httpd: Session ID: 63
I (456099) wifi_hdlr: Creds received belkin.36f7 64c886fd
I (456109) protocomm_httpd: ADI Done
I (456189) protocomm_httpd: Session ID: 63
APP Got: ANMjgBHkgctVDuEpQkZQ amzn1.application-oa2-client.a5b0d0c6a5f546499d1e5043f3515e6b amzn://com.espressif.provision abcd1234
I (456199) protocomm_httpd: ADI Done
W (456259) wifi: rx ampdu exist: tid=0 new <ssn=1156 win=0> old <ssn=1156 win=6>
I (456379) protocomm_httpd: Session ID: 63
I (456389) conn_mgr: Received event: 66
I (456389) alexa: got station network credential recieved event
I (456389) conn_mgr: Received event: 0
I (456389) sm_sta: In station start
I (456399) protocomm_httpd: ADI Done
I (456399) sm_sta: Connecting to SSID: belkin.36f7
I (456409) wifi: mode : sta (80:7d:3a:e1:4f:a0) + softAP (80:7d:3a:e1:4f:a1)
I (456419) conn_mgr: SYSTEM_EVENT_STA_START
I (456419) conn_mgr: Received event: 128
I (456469) protocomm_httpd: Session ID: 63
Connecting state
I (456469) protocomm_httpd: ADI Done
I (456699) wifi: n:1 1, o:1 0, ap:1 1, sta:1 1, prof:1
I (457449) wifi: state: init -> auth (b0)
I (457449) wifi: state: auth -> assoc (0)
I (457479) wifi: state: assoc -> run (10)
I (457659) wifi: connected with belkin.36f7, channel 1
I (457659) wifi: pm start, type: 1

I (457659) conn_mgr: SYSTEM_EVENT_STA_CONNECTED
I (457659) conn_mgr: Received event: 128
I (457659) alexa: got station connected event
W (458259) wifi: rx ampdu exist: tid=0 new <ssn=1232 win=0> old <ssn=1226 win=6>
I (459109) event: sta ip: 192.168.2.8, mask: 255.255.255.0, gw: 192.168.2.1
I (459109) conn_mgr: SYSTEM_EVENT_STA_GOT_IP
I (459109) conn_mgr: got ip:192.168.2.8
I (459109) conn_mgr: Received event: 128
I (459119) alexa: got IPv4:192.168.2.8
W (459269) wifi: rx ampdu exist: tid=0 new <ssn=1254 win=0> old <ssn=1248 win=6>
W (460269) wifi: rx ampdu exist: tid=0 new <ssn=1296 win=0> old <ssn=1296 win=6>
W (461269) wifi: rx ampdu exist: tid=0 new <ssn=1329 win=0> old <ssn=1329 win=6>
I (461719) protocomm_httpd: Session ID: 63
Connected state
I (461719) protocomm_httpd: ADI Done
W (462269) wifi: rx ampdu exist: tid=0 new <ssn=1357 win=0> old <ssn=1357 win=6>
W (463269) wifi: rx ampdu exist: tid=0 new <ssn=1379 win=0> old <ssn=1379 win=6>
W (464279) wifi: rx ampdu exist: tid=0 new <ssn=1397 win=0> old <ssn=1397 win=6>
W (465279) wifi: rx ampdu exist: tid=0 new <ssn=1428 win=0> old <ssn=1419 win=6>
W (466279) wifi: rx ampdu exist: tid=0 new <ssn=1447 win=0> old <ssn=1447 win=6>
W (467279) wifi: rx ampdu exist: tid=0 new <ssn=1482 win=0> old <ssn=1483 win=6>
W (468289) wifi: rx ampdu exist: tid=0 new <ssn=1516 win=0> old <ssn=1516 win=6>
W (469289) wifi: rx ampdu exist: tid=0 new <ssn=1550 win=0> old <ssn=1549 win=6>
W (470299) wifi: rx ampdu exist: tid=0 new <ssn=1582 win=0> old <ssn=1581 win=6>
W (471299) wifi: rx ampdu exist: tid=0 new <ssn=1603 win=0> old <ssn=1603 win=6>
W (472299) wifi: rx ampdu exist: tid=0 new <ssn=1631 win=0> old <ssn=1631 win=6>
W (473299) wifi: rx ampdu exist: tid=0 new <ssn=1663 win=0> old <ssn=1663 win=6>
I (474119) wifi: station: 8c:79:67:c8:70:ab leave, AID = 1
I (474119) wifi: n:1 1, o:1 1, ap:1 1, sta:1 1, prof:1
I (474119) wifi: mode : sta (80:7d:3a:e1:4f:a0)
I (474119) conn_mgr: Received event: 65
W (474129) httpd_txrx: httpd_default_recv: error in recv = 113
I (474129) protocomm_httpd: Removing endpoint : prov-config
W (474139) httpd_txrx: httpd_resp_send_err: 408 Request Timeout - Server closed this connection
I (474149) protocomm_httpd: Removing endpoint : avsconfig
W (474159) httpd_txrx: httpd_default_send: error in send = 113
I (474159) protocomm_httpd: Removing endpoint : prov-session
I (475169) conn_mgr: Received event: 128
I (475169) conn_mgr: Received event: 128
I (475169) I2S: DMA Malloc info, datalen=blocksize=600, dma_buf_count=3
I (475169) I2S: DMA Malloc info, datalen=blocksize=600, dma_buf_count=3
I (475179) I2S: PLL_D2: Req RATE: 16000, real rate: 16025.000, BITS: 16, CLKM: 39, BCK: 8, MCLK: 4096000.000, SCLK: 512800.000000, diva: 64, divb: 4
I (475189) gpio: GPIO[22]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:0
I (475199) gpio: GPIO[19]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:0
I (475209) UI_LED: LED initialized
I (475219) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:1
I (475219) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 1| Intr:3
I (475229) gpio: GPIO[21]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (475259) dsp: Created I2S audio stream
I (475259) audio_stream: Starting i2s_reader stream
Starting audio stream i2s_reader
W (475259) I2S: I2S driver already installed
.......................Init i2s stream...............
I (475269) audio_stream: Stream i2s_reader Event Started
I (475279) dsp: Reader stream event 2
speech_recognizer: Ignoring data in idle state
speech_recognizer: Ignoring data in idle state
speech_recognizer: Ignoring data in idle state
Stopping audio stream i2s_reader
speech_recognizer: Ignoring data in idle state
I (475299) audio_stream: Stream i2s_reader Event Stopped
I (475309) dsp: Reader stream event 3
Generated stopped event for stream i2s_reader
I (475319) I2S: PLL_D2: Req RATE: 48000, real rate: 48076.000, BITS: 16, CLKM: 13, BCK: 8, MCLK: 12292917.167, SCLK: 1538432.000000, diva: 64, divb: 1
I (475329) audio_stream: Starting playback_writer stream
Starting audio stream playback_writer
I (475339) audio_stream: Stream playback_writer Event Started
E (475349) avs-nvs-util: Error opening avs namespace!
I (475349) [speaker]: Using default volume
I (475359) LYRAT_CB: Volume changed to 40
I (475359) auth-delegate-config: Returning auth delegate companion app configuration
I (475369) [auth-delegate]: Auth delegate with comp app ANMjgBHkgctVDuEpQkZQ amzn1.application-oa2-client.a5b0d0c6a5f546499d1e5043f3515e6b amzn://com.espressif.provision abcd1234
I (479699) auth-delegate-config: Set client ID amzn1.application-oa2-client.a5b0d0c6a5f546499d1e5043f3515e6b and refresh token Atzr|IwEBINyiji6thlJDhNSMVXaPq7DFszWjuVK9TntaVLGQF-o2G4oCJQSoQYzX2AHESNK5TZ-ubcXahYDBZ7IrvQRdfTm5L9ihKYwbn2pmx3G6vhI78pdZ_NmPjJVDEbDectEDWnOQ9nOB9Gwa8-0fAjUsHA9k-GwlAPMPmNMzw4bPyDKVuLFgKKQwYuMHs8dyS_oYbpcehKrD7jx4eWZ3I6o4AMuKm7y7bHKCO75MSxBfGv7l16YqWKYMmsnarHNcYLv_CHQbNl-8XxMbRp1fbzx6-7LMGpsnVjUQVpKfKv4ZSnN-Js72KG-sqwlHm939d08a8VkMO0wyq3VUaCG9Uw83YBz4Pnd20ctmBV0g1CQen47uR5MrZzwbMYkKpHsngymL5hUxDrLe17bElm_CZX94i6C_eIrngf-h-sdjKGrMioUyrvOgWnIyZCSqzebPF4Y2gv4J5KHwBVhfGaGLHz2OEa-tl3laCARmQ38nQyBcd5GQKoU5QmK6dQk85cHTpVk25SVBR-L8mqWJAwsr5DydWf3Xre7GgESW3fwksg2eplA7iw in NVS successfully
I (479759) [auth-delegate]: Authentication Done !
I (479759) avs-nvs-util: No value set for: cap_version
I (479769) capabilities: capabilities version not found in NVS or version is different

设备连接WiFi的指示灯一直不亮，这是怎么回事？谢谢回答

**Comment by avsheth** [comment]
Hi @xiaoseyihe Print on the app is incorrect. We already have removed it and will be updated in the next release.
From your logs, I can see that device was successfully connected to the AP and Alexa authentication was also successful.

**Comment by xiaoseyihe** [comment]
@avsheth  问题已经解决了，应该和WIFI有关。再请教个问题，怎么重配WIFI，比如设备之前连接 一个WIFI，现在让它连接另一个WIFI环境，在出现“Now connect your phone to the wifi network with a name like: Esp-Alexa-xxxx”,但是我再WiFi列表中找不到Esp-Alexa-xxxx，。之前的配网需要重置吗？或者需要什么操作，谢谢

**Comment by avsheth** [comment]
Hi @xiaoseyihe 
If I understood it correctly, you want to change your WiFi network on the device.
Once device is connected to one network, softAP on the device is turned off.
You can use CLI to set new credentials like below (press Enter to bring up CLI):
>> nvs-set cm ssid string <your ssid>
>> nvs-set cm pass string <your pass>

**Comment by xiaoseyihe** [comment]
Thank you for your answers, I have achieved it.
